import { Router } from 'express';
import authRouter from './modules/auth/router.js';
import { requireAuth } from './middleware/auth.js';
import organizationsRouter from './modules/organizations/router.js';
import apiKeysRouter from './modules/api-keys/router.js';
import customersRouter from './modules/customers/router.js';
import metersRouter from './modules/meters/router.js';
import usageEventsRouter from './modules/usage-events/router.js';
import usageAggregationRouter from './modules/usage-aggregation/router.js';
import productsRouter from './modules/products/router.js';
import pricingRouter from './modules/pricing/router.js';
import plansRouter from './modules/plans/router.js';
import subscriptionsRouter from './modules/subscriptions/router.js';
import billingPeriodsRouter from './modules/billing-periods/router.js';
import ledgerRouter from './modules/ledger/router.js';
import invoicesRouter from './modules/invoices/router.js';
import paymentsRouter from './modules/payments/router.js';
import webhooksInboundRouter from './modules/webhooks-inbound/router.js';
import creditsRouter from './modules/credits/router.js';
import adjustmentsRouter from './modules/adjustments/router.js';
import refundsRouter from './modules/refunds/router.js';
import couponsRouter from './modules/coupons/router.js';
import taxRouter from './modules/tax/router.js';
import revenueRouter from './modules/revenue/router.js';
import reportsRouter from './modules/reports/router.js';
import alertsRouter from './modules/alerts/router.js';
import notificationsRouter from './modules/notifications/router.js';
import developerRouter from './modules/developer/router.js';
import eventLogRouter from './modules/event-log/router.js';
import webhooksOutboundRouter from './modules/webhooks-outbound/router.js';
import auditRouter from './modules/audit/router.js';
import supportRouter from './modules/support/router.js';
import adminRouter from './modules/admin/router.js';
import jobsRouter from './modules/jobs/router.js';
import observabilityRouter from './modules/observability/router.js';
import featureFlagsRouter from './modules/feature-flags/router.js';
import settingsRouter from './modules/settings/router.js';
import mobileRouter from './modules/mobile/router.js';

export const apiRouter=Router();
apiRouter.use('/auth',authRouter);
apiRouter.use('/organizations',requireAuth,organizationsRouter);
apiRouter.use('/api-keys',requireAuth,apiKeysRouter);
apiRouter.use('/customers',requireAuth,customersRouter);
apiRouter.use('/meters',requireAuth,metersRouter);
apiRouter.use('/usage-events',requireAuth,usageEventsRouter);
apiRouter.use('/usage-aggregation',requireAuth,usageAggregationRouter);
apiRouter.use('/products',requireAuth,productsRouter);
apiRouter.use('/pricing',requireAuth,pricingRouter);
apiRouter.use('/plans',requireAuth,plansRouter);
apiRouter.use('/subscriptions',requireAuth,subscriptionsRouter);
apiRouter.use('/billing-periods',requireAuth,billingPeriodsRouter);
apiRouter.use('/ledger',requireAuth,ledgerRouter);
apiRouter.use('/invoices',requireAuth,invoicesRouter);
apiRouter.use('/payments',requireAuth,paymentsRouter);
apiRouter.use('/webhooks-inbound',requireAuth,webhooksInboundRouter);
apiRouter.use('/credits',requireAuth,creditsRouter);
apiRouter.use('/adjustments',requireAuth,adjustmentsRouter);
apiRouter.use('/refunds',requireAuth,refundsRouter);
apiRouter.use('/coupons',requireAuth,couponsRouter);
apiRouter.use('/tax',requireAuth,taxRouter);
apiRouter.use('/revenue',requireAuth,revenueRouter);
apiRouter.use('/reports',requireAuth,reportsRouter);
apiRouter.use('/alerts',requireAuth,alertsRouter);
apiRouter.use('/notifications',requireAuth,notificationsRouter);
apiRouter.use('/developer',requireAuth,developerRouter);
apiRouter.use('/event-log',requireAuth,eventLogRouter);
apiRouter.use('/webhooks-outbound',requireAuth,webhooksOutboundRouter);
apiRouter.use('/audit',requireAuth,auditRouter);
apiRouter.use('/support',requireAuth,supportRouter);
apiRouter.use('/admin',requireAuth,adminRouter);
apiRouter.use('/jobs',requireAuth,jobsRouter);
apiRouter.use('/observability',requireAuth,observabilityRouter);
apiRouter.use('/feature-flags',requireAuth,featureFlagsRouter);
apiRouter.use('/settings',requireAuth,settingsRouter);
apiRouter.use('/mobile',requireAuth,mobileRouter);
